### ISSUE TITLE
Add support for configuring teams

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/github-configurer#2]
Similar to `collaborators`, the config might look something like this:

```yml
teams:
  - name: engineers
    permission: admin
  - name: project-managers
    permission: push
  - name: bosses
    permission: pull
```
